/**
 * AUTO-GENERATED by scripts/generate-qa-map.ts
 * 직접 수정하지 마세요. pnpm generate:qa-map 으로 갱신합니다.
 *
 * 생성 기준: Figma Component Set에서 Interaction=Rest variant만 추출
 * 마지막 생성: Figma MCP (2026-06-14)
 */
export const AUTO_GENERATED_QA_MAP: Record<string, string> = {

  // ── Button (Office) ─────────────────────────────────────────────────────────
  // Component Set: 205:2273 / 필터: Interaction=Rest, Icon Position=none
  // qaId: btn-{role}-{style}-{size}[-disabled]

  'btn-brand-solid-xs': '205:1217',
  'btn-brand-solid-sm': '205:1250',
  'btn-brand-solid-md': '205:1283',
  'btn-brand-solid-lg': '205:1316',
  'btn-brand-solid-xs-disabled': '205:1239',
  'btn-brand-solid-sm-disabled': '205:1272',
  'btn-brand-solid-md-disabled': '205:1305',
  'btn-brand-solid-lg-disabled': '205:1338',

  'btn-brand-outline-xs': '205:1349',
  'btn-brand-outline-sm': '205:1382',
  'btn-brand-outline-md': '205:1415',
  'btn-brand-outline-lg': '205:1448',
  'btn-brand-outline-xs-disabled': '205:1371',
  'btn-brand-outline-sm-disabled': '205:1404',
  'btn-brand-outline-md-disabled': '205:1437',
  'btn-brand-outline-lg-disabled': '205:1470',

  'btn-brand-text-xs': '205:1481',
  'btn-brand-text-sm': '205:1514',
  'btn-brand-text-md': '205:1547',
  'btn-brand-text-lg': '205:1580',
  'btn-brand-text-xs-disabled': '205:1503',
  'btn-brand-text-sm-disabled': '205:1536',
  'btn-brand-text-md-disabled': '205:1569',
  'btn-brand-text-lg-disabled': '205:1602',

  'btn-neutral-solid-xs': '205:1613',
  'btn-neutral-solid-sm': '205:1646',
  'btn-neutral-solid-md': '205:1679',
  'btn-neutral-solid-lg': '205:1712',
  'btn-neutral-solid-xs-disabled': '205:1635',
  'btn-neutral-solid-sm-disabled': '205:1668',
  'btn-neutral-solid-md-disabled': '205:1701',
  'btn-neutral-solid-lg-disabled': '205:1734',

  'btn-neutral-outline-xs': '205:1745',
  'btn-neutral-outline-sm': '205:1778',
  'btn-neutral-outline-md': '205:1811',
  'btn-neutral-outline-lg': '205:1844',
  'btn-neutral-outline-xs-disabled': '205:1767',
  'btn-neutral-outline-sm-disabled': '205:1800',
  'btn-neutral-outline-md-disabled': '205:1833',
  'btn-neutral-outline-lg-disabled': '205:1866',

  'btn-neutral-ghost-xs': '205:1877',
  'btn-neutral-ghost-sm': '205:1910',
  'btn-neutral-ghost-md': '205:1943',
  'btn-neutral-ghost-lg': '205:1976',
  'btn-neutral-ghost-xs-disabled': '205:1899',
  'btn-neutral-ghost-sm-disabled': '205:1932',
  'btn-neutral-ghost-md-disabled': '205:1965',
  'btn-neutral-ghost-lg-disabled': '205:1998',

  'btn-destructive-solid-xs': '205:2009',
  'btn-destructive-solid-sm': '205:2042',
  'btn-destructive-solid-md': '205:2075',
  'btn-destructive-solid-lg': '205:2108',
  'btn-destructive-solid-xs-disabled': '205:2031',
  'btn-destructive-solid-sm-disabled': '205:2064',
  'btn-destructive-solid-md-disabled': '205:2097',
  'btn-destructive-solid-lg-disabled': '205:2130',

  'btn-critical-solid-xs': '205:2141',
  'btn-critical-solid-sm': '205:2174',
  'btn-critical-solid-md': '205:2207',
  'btn-critical-solid-lg': '205:2240',
  'btn-critical-solid-xs-disabled': '205:2163',
  'btn-critical-solid-sm-disabled': '205:2196',
  'btn-critical-solid-md-disabled': '205:2229',
  'btn-critical-solid-lg-disabled': '205:2262',

  // ── ButtonIconOnly (Office) ──────────────────────────────────────────────────
  // Component Set: 232:1354 / 필터: Interaction=Rest
  // qaId: btn-icon-{role}-{style}-{size}[-disabled]

  'btn-icon-brand-solid-xs': '232:1210',
  'btn-icon-brand-solid-sm': '232:1216',
  'btn-icon-brand-solid-md': '232:1222',
  'btn-icon-brand-solid-xs-disabled': '232:1214',
  'btn-icon-brand-solid-sm-disabled': '232:1220',
  'btn-icon-brand-solid-md-disabled': '232:1226',

  'btn-icon-brand-outline-xs': '232:1228',
  'btn-icon-brand-outline-sm': '232:1234',
  'btn-icon-brand-outline-md': '232:1240',
  'btn-icon-brand-outline-xs-disabled': '232:1232',
  'btn-icon-brand-outline-sm-disabled': '232:1238',
  'btn-icon-brand-outline-md-disabled': '232:1244',

  'btn-icon-brand-text-xs': '232:1246',
  'btn-icon-brand-text-sm': '232:1252',
  'btn-icon-brand-text-md': '232:1258',
  'btn-icon-brand-text-xs-disabled': '232:1250',
  'btn-icon-brand-text-sm-disabled': '232:1256',
  'btn-icon-brand-text-md-disabled': '232:1262',

  'btn-icon-neutral-solid-xs': '232:1264',
  'btn-icon-neutral-solid-sm': '232:1270',
  'btn-icon-neutral-solid-md': '232:1276',
  'btn-icon-neutral-solid-xs-disabled': '232:1268',
  'btn-icon-neutral-solid-sm-disabled': '232:1274',
  'btn-icon-neutral-solid-md-disabled': '232:1280',

  'btn-icon-neutral-outline-xs': '232:1282',
  'btn-icon-neutral-outline-sm': '232:1288',
  'btn-icon-neutral-outline-md': '232:1294',
  'btn-icon-neutral-outline-xs-disabled': '232:1286',
  'btn-icon-neutral-outline-sm-disabled': '232:1292',
  'btn-icon-neutral-outline-md-disabled': '232:1298',

  'btn-icon-neutral-ghost-xs': '232:1300',
  'btn-icon-neutral-ghost-sm': '232:1306',
  'btn-icon-neutral-ghost-md': '232:1312',
  'btn-icon-neutral-ghost-xs-disabled': '232:1304',
  'btn-icon-neutral-ghost-sm-disabled': '232:1310',
  'btn-icon-neutral-ghost-md-disabled': '232:1316',

  'btn-icon-destructive-solid-xs': '232:1318',
  'btn-icon-destructive-solid-sm': '232:1324',
  'btn-icon-destructive-solid-md': '232:1330',
  'btn-icon-destructive-solid-xs-disabled': '232:1322',
  'btn-icon-destructive-solid-sm-disabled': '232:1328',
  'btn-icon-destructive-solid-md-disabled': '232:1334',

  'btn-icon-critical-solid-xs': '232:1336',
  'btn-icon-critical-solid-sm': '232:1342',
  'btn-icon-critical-solid-md': '232:1348',
  'btn-icon-critical-solid-xs-disabled': '232:1340',
  'btn-icon-critical-solid-sm-disabled': '232:1346',
  'btn-icon-critical-solid-md-disabled': '232:1352',

  // ── TextInput (Office) ───────────────────────────────────────────────────────
  // Component Set: 216:4816 / 필터: Interaction=Rest, Style=Boxed, Alignment=Left
  // qaId: input-{size}-{availability}-{validation}
  // Validation=Warning은 Figma에 미존재 → 디자이너 추가 요청 대상

  'input-sm-enabled-none': '295:656',
  'input-sm-enabled-error': '216:4760',
  'input-sm-enabled-success': '278:3162',
  'input-sm-disabled-none': '216:4768',
  'input-sm-readonly-none': '263:331',

  'input-md-enabled-none': '263:353',
  'input-md-enabled-error': '263:374',
  'input-md-enabled-success': '278:3186',
  'input-md-disabled-none': '263:381',
  'input-md-readonly-none': '263:388',

  'input-lg-enabled-none': '263:490',
  'input-lg-enabled-error': '263:511',
  'input-lg-enabled-success': '278:3208',
  'input-lg-disabled-none': '263:518',
  'input-lg-readonly-none': '263:525',

  // ── LNB · NavItem ────────────────────────────────────────────────────────────
  // Component Set: 338:1126 / 필터: Interaction=Rest
  // qaId: lnb-nav-l{level}-{stateLabel}
  // stateLabel 우선순위 (NavItem.tsx:127): dragging > dragover > disabled > selected > rest

  'lnb-nav-l1-rest': '338:1127',
  'lnb-nav-l2-rest': '346:427',
  'lnb-nav-l3-rest': '346:571',

  'lnb-nav-l1-selected': '338:1914',
  'lnb-nav-l2-selected': '346:463',
  'lnb-nav-l3-selected': '346:607',

  'lnb-nav-l1-disabled': '338:1956',
  'lnb-nav-l2-disabled': '346:445',
  'lnb-nav-l3-disabled': '346:589',

  'lnb-nav-l1-dragging': '338:2051',
  'lnb-nav-l2-dragging': '346:433',
  'lnb-nav-l3-dragging': '346:577',

  'lnb-nav-l1-dragover': '338:2137',
  'lnb-nav-l2-dragover': '346:439',
  'lnb-nav-l3-dragover': '346:583',

  // ── LNB · SectionHeader ──────────────────────────────────────────────────────
  // Component Set: 338:2489 / 필터: Interaction=Rest
  // qaId: lnb-section-l{level}-{stateLabel}
  // expanded/collapsed는 동일 base variant (chevron 회전만 다름) → 동일 node-id

  'lnb-section-l1-expanded': '338:2490',
  'lnb-section-l2-expanded': '349:194',
  'lnb-section-l1-collapsed': '338:2490',
  'lnb-section-l2-collapsed': '349:194',

  'lnb-section-l1-disabled': '338:2508',
  'lnb-section-l2-disabled': '349:212',

  'lnb-section-l1-dragging': '338:2496',
  'lnb-section-l2-dragging': '349:200',

  'lnb-section-l1-dragover': '338:2502',
  'lnb-section-l2-dragover': '349:206',

  // ── LNB · ActionButton ───────────────────────────────────────────────────────
  // Component Set: 363:721 / 필터: Interaction=Rest
  // qaId: lnb-action-rest[-disabled]

  'lnb-action-rest': '363:720',
  'lnb-action-rest-disabled': '363:727',
};
